name: mdc_web_example_simple
description: Example usage of the mdc_web package.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
 mdc_web:
   path: ../..

dev_dependencies:
  build_runner: ^1.11.0
  build_web_compilers: ^2.16.0
  sass_builder: ^2.1.0

